# Generated by Django 5.1.3 on 2024-11-12 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField()),
                ('industry', models.CharField(max_length=30)),
                ('career_stage', models.CharField(choices=[('Student', 'Student'), ('1 - 3 years', '1 - 3 years'), ('4 - 6 years', '4 - 6 years'), ('7 - 9 years', '7 - 9 years'), ('10+ years', '10+ years')], default='Student', max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('industry_interest', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=30)),
                ('major_minor', models.CharField(max_length=30)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('graduation_year', models.IntegerField(max_length=4)),
                ('volunteer_interest', models.CharField(max_length=30)),
                ('date_updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Prefer not to say', 'Prefer not to say')], default='Female', max_length=30)),
                ('image', models.ImageField(blank=True, default='images/profilepicture.jpg', null=True, upload_to='images/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('date_updated', models.DateField(auto_now=True)),
                ('last_seen', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
