# Generated by Django 5.1.3 on 2025-02-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_profession_gpa_alter_profession_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='graduation_year',
            field=models.IntegerField(default=1900),
        ),
    ]
