# Generated by Django 5.1.3 on 2025-02-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_profession_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
