# Generated by Django 5.1.3 on 2025-05-08 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_profile_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('industry', models.CharField(max_length=50)),
                ('application_link', models.URLField(max_length=500)),
                ('application_deadline', models.DateField()),
                ('employer_logo', models.ImageField(blank=True, default='employer_logos/default_logo.jpg', upload_to='employer_logos/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
