# Generated by Django 5.1.3 on 2025-06-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='company',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='profession',
            name='position',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='profession',
            name='school',
            field=models.CharField(max_length=60),
        ),
    ]
