# Generated by Django 5.1.3 on 2025-07-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_profession_company_alter_profession_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Non-Binary', 'Non-Binary'), ('Transgender', 'Transgender'), ('Not Listed', 'Not Listed'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=30),
        ),
    ]
